"""
Phase 1: PDF Processing & Pre-Extraction
Converts uploaded PDF to individual high-res page images.
"""
import os
from pathlib import Path
from typing import List, Optional
import tempfile
from pdf2image import convert_from_path, pdfinfo_from_path
from PIL import Image
import logging

# Manga pages at 300 DPI legitimately exceed PIL's default pixel limit
Image.MAX_IMAGE_PIXELS = None

logger = logging.getLogger(__name__)


class PDFProcessor:
    """Handles PDF to image conversion."""

    def __init__(self, dpi: int = 150, output_dir: Optional[Path] = None):
        """
        Initialize PDF processor.

        Args:
            dpi: Resolution for PDF conversion (default 150 for faster rendering)
            output_dir: Directory to save page images
        """
        self.dpi = dpi
        self.output_dir = output_dir

    def _get_poppler_path(self) -> Optional[str]:
        """Get the path to local poppler binaries if they exist."""
        local_poppler = Path(__file__).parent.parent / "poppler" / "poppler-24.08.0" / "Library" / "bin"
        if local_poppler.exists():
            return str(local_poppler)
        return None

    def convert_pdf_to_pages(
        self,
        pdf_path: Path,
        output_dir: Optional[Path] = None
    ) -> List[Path]:
        """
        Convert a PDF file to individual page images.

        Args:
            pdf_path: Path to the PDF file
            output_dir: Directory to save page images (uses instance output_dir if not provided)

        Returns:
            List of paths to the generated page images

        Raises:
            FileNotFoundError: If PDF doesn't exist
            ValueError: If PDF conversion fails
        """
        pdf_path = Path(pdf_path)

        if not pdf_path.exists():
            raise FileNotFoundError(f"PDF file not found: {pdf_path}")

        save_dir = Path(output_dir) if output_dir else self.output_dir

        if save_dir is None:
            save_dir = Path(tempfile.mkdtemp(prefix="manga_pages_"))

        save_dir.mkdir(parents=True, exist_ok=True)

        logger.info(f"Converting PDF to images at {self.dpi} DPI...")

        try:
            poppler_path = self._get_poppler_path()
            logger.info("Executing fast PDF conversion via Poppler direct-to-disk...")
            
            # Convert PDF and write images directly to disk using Poppler
            # format 'png' is handled natively by pdftoppm
            page_paths_raw = convert_from_path(
                str(pdf_path),
                dpi=self.dpi,
                fmt='png',
                output_folder=str(save_dir),
                poppler_path=poppler_path,
                paths_only=True,
                thread_count=4
            )
            
            if not page_paths_raw:
                raise ValueError("No pages extracted from PDF")

            import re
            def get_page_num(p_str):
                m = re.search(r'-(\d+)\.png$', Path(p_str).name, re.IGNORECASE)
                return int(m.group(1)) if m else 0

            page_paths_raw = sorted(page_paths_raw, key=get_page_num)

            page_paths = []
            total_pages = len(page_paths_raw)

            for i, raw_path_str in enumerate(page_paths_raw, start=1):
                raw_path = Path(raw_path_str)
                page_filename = f"page_{i:03d}.png"
                page_path = save_dir / page_filename
                
                # Rename the temp file generated by pdf2image to page_00X.png
                raw_path.rename(page_path)
                page_paths.append(page_path)
                logger.info(f"Saved page {i}/{total_pages}: {page_path}")

            logger.info(f"Successfully converted {len(page_paths)} pages")
            return page_paths

        except Exception as e:
            logger.error(f"Failed to convert PDF: {e}")
            raise ValueError(f"PDF conversion failed: {e}")

    def validate_pdf(self, pdf_path: Path) -> bool:
        """
        Validate that a file is a readable PDF.

        Args:
            pdf_path: Path to the PDF file

        Returns:
            True if valid, False otherwise
        """
        pdf_path = Path(pdf_path)

        if not pdf_path.exists():
            return False

        if pdf_path.suffix.lower() != '.pdf':
            return False

        try:
            # Try to read first page
            pages = convert_from_path(
                str(pdf_path),
                first_page=1,
                last_page=1,
                poppler_path=self._get_poppler_path()
            )
            return len(pages) > 0
        except Exception as e:
            logger.error(f"validate_pdf failed: {e}")
            return False
